### ISSUE TITLE
Create Wallet + Read-Only Prompts in Vaults UI are not prominent enough

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#152] opened 2023-06-27 15:16 UTC
## What is the Problem Being Solved?

When a user navigates to Vaults UI, they are prompted to create a wallet via the smart wallet UI - this pop-up appears in bottom right corner of dapp UI and is not prominent/explicit enough causing some users to miss it. 

It would be better UX to make this prompt appear front and center, likely larger so it cannot be missed.

## Description of the Design

Perhaps use disclaimer style and size which is abundantly clear but open to more nuanced ways to do this.

## Security Considerations
N/A

**Comment by otoole-brendan** [comment] 2023-06-27 15:16
Same exists for PSM - separate ticket coming...

**Comment by samsiegart** [comment] 2024-05-08 18:31
dupe of https://github.com/Agoric/dapp-inter/issues/189

**Closed by samsiegart** 2024-05-08 18:31 UTC
Labels: enhancement
